const char *src_map_frag_glsl = 
	"#version 330 core\n"
	"\n"
	"in vec4 color;\n"
	"out vec4 fragColor;\n"
	"\n"
	"void main()\n"
	"{\n"
	"\tfragColor = color;\n"
	"}\n";
const char *src_map_vert_glsl = 
	"#version 330 core\n"
	"\n"
	"out vec4 color;\n"
	"\n"
	"void main()\n"
	"{\n"
	"\tif(gl_VertexID == 0) {\n"
	"\t\tgl_Position = vec4(0, 0, 0, 1);\n"
	"\t\tcolor = vec4(1, 0, 0, 1);\n"
	"\t}\n"
	"\telse if(gl_VertexID == 1) {\n"
	"\t\tgl_Position = vec4(1, 0, 0, 1);\n"
	"\t\tcolor = vec4(0, 1, 0, 1);\n"
	"\t}\n"
	"\telse if(gl_VertexID == 2) {\n"
	"\t\tgl_Position = vec4(0, 1, 0, 1);\n"
	"\t\tcolor = vec4(0, 0, 1, 1);\n"
	"\t}\n"
	"}\n";
